language: c
sudo: true
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.7"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - sudo rm -rf ~/arduino_ide/libraries/AsyncTCP
  - sudo rm -rf ~/arduino_ide/libraries/ESPAsyncTCP
  - sudo rm -rf ~/arduino_ide/libraries/ESPAsyncWebServer
  - sudo rm -rf ~/arduino_ide/libraries/ArduinoJson
  - sudo rm -rf ~/arduino_ide/libraries/ESP-DASH
  - git clone https://github.com/me-no-dev/AsyncTCP.git ~/arduino_ide/libraries/AsyncTCP
  - git clone https://github.com/me-no-dev/ESPAsyncTCP.git ~/arduino_ide/libraries/ESPAsyncTCP
  - git clone https://github.com/me-no-dev/ESPAsyncWebServer.git ~/arduino_ide/libraries/ESPAsyncWebServer
  - git clone -b 6.x https://github.com/bblanchon/ArduinoJson.git ~/arduino_ide/libraries/ArduinoJson
  - git clone https://github.com/ayushsharma82/ESP-DASH.git ~/arduino_ide/libraries/ESP-DASH
script:
  - build_platform esp8266
notifications:
  email:
    on_success: change
    on_failure: change
